#!/bin/sh 

check_process() {
  [ "$1" = "" ]  && return 0
  [ `pgrep -n $1` ] && return 1 || return 0
}

while [ 1 ]; do 
  # timestamp
  ts=`date +%T`

  check_process "dnscrypt-proxy"
  [ $? -eq 0 ] && `/etc/init.d/dnscrypt-proxy restart`
  sleep 10
done
